// 백엔드 연결 전 UI 확인용 목업 데이터
import type { HelpRequest } from '../types';

export const MOCK_REQUESTS: HelpRequest[] = [
  {
    id: 1,
    title: '은행 계좌 개설 도와주실 분 구해요',
    description:
      '신한은행에서 외국인 계좌 개설하려는데 서류 준비부터 같이 가주실 분 있나요?\n\n필요한 서류가 뭔지도 잘 모르고, 은행 직원이랑 한국어로 대화하는 게 너무 어려워요. 근처 신한은행 같이 가주실 분 구합니다. 시간은 평일 오전에 가능해요!',
    category: 'BANK',
    helpMethod: 'OFFLINE',
    status: 'WAITING',
    requester: {
      id: 1,
      email: 'li@test.com',
      nickname: '리웨이',
      userType: 'INTERNATIONAL',
      university: '한양대학교',
      rating: 4.5,
      helpCount: 2,
      createdAt: '2026-03-10',
    },
    createdAt: '2026-03-15T09:00:00',
    updatedAt: '2026-03-15T09:00:00',
  },
  {
    id: 2,
    title: '병원 예약 전화 통역 부탁드려요',
    description:
      '내과 예약 전화해야 하는데 한국어가 아직 서툴러서 통역 좀 도와주실 수 있나요?\n\n전화 통화 5분 정도면 될 것 같아요. 가능하시면 채팅으로 먼저 연락 주시면 일정 맞춰볼게요.',
    category: 'HOSPITAL',
    helpMethod: 'CHAT',
    status: 'WAITING',
    requester: {
      id: 2,
      email: 'ahmed@test.com',
      nickname: '아흐메드',
      userType: 'INTERNATIONAL',
      university: '연세대학교',
      rating: 4.8,
      helpCount: 0,
      createdAt: '2026-03-12',
    },
    createdAt: '2026-03-15T10:30:00',
    updatedAt: '2026-03-15T10:30:00',
  },
  {
    id: 3,
    title: '수강신청 방법 알려주실 분!',
    description:
      '포탈에서 수강신청하는 방법을 잘 모르겠어요. 영상통화로 같이 해주실 수 있나요?\n\n수강신청 날짜가 곧 다가오는데 혼자 하기가 너무 어렵네요. 학교 포탈 사용법, 수강 바구니 담는 법 등을 알려주시면 정말 감사하겠습니다!',
    category: 'SCHOOL',
    helpMethod: 'VIDEO_CALL',
    status: 'WAITING',
    requester: {
      id: 3,
      email: 'maria@test.com',
      nickname: '마리아',
      userType: 'INTERNATIONAL',
      university: '성균관대학교',
      rating: 5.0,
      helpCount: 1,
      createdAt: '2026-03-11',
    },
    createdAt: '2026-03-15T11:00:00',
    updatedAt: '2026-03-15T11:00:00',
  },
  {
    id: 4,
    title: '주민등록증 발급 절차 안내 부탁해요',
    description:
      '외국인 등록증 발급받으러 출입국사무소 가야 하는데 어떻게 하는지 알려주실 분!\n\n어떤 서류를 준비해야 하는지, 예약은 어떻게 하는지 너무 복잡해서 도움 요청드립니다.',
    category: 'DAILY',
    helpMethod: 'CHAT',
    status: 'MATCHED',
    requester: {
      id: 4,
      email: 'chen@test.com',
      nickname: '천밍',
      userType: 'INTERNATIONAL',
      university: '고려대학교',
      rating: 4.2,
      helpCount: 3,
      createdAt: '2026-03-08',
    },
    createdAt: '2026-03-14T15:00:00',
    updatedAt: '2026-03-14T16:00:00',
  },
  {
    id: 5,
    title: '택배 수령 주소 작성 도움 요청',
    description: '온라인 쇼핑몰에서 물건 주문하려는데 한국 주소 형식을 잘 모르겠어요. 배송지 주소 올바르게 입력하는 방법 알려주실 수 있나요?',
    category: 'DAILY',
    helpMethod: 'CHAT',
    status: 'WAITING',
    requester: {
      id: 5,
      email: 'nguyen@test.com',
      nickname: '응우옌',
      userType: 'INTERNATIONAL',
      university: '국민대학교',
      rating: 4.6,
      helpCount: 0,
      createdAt: '2026-03-13',
    },
    createdAt: '2026-03-15T12:00:00',
    updatedAt: '2026-03-15T12:00:00',
  },
  {
    id: 6,
    title: '장학금 신청서 한국어 작성 도와주실 분',
    description: '국가장학금 신청서를 작성해야 하는데 한국어로 자기소개와 학업계획서를 써야 해요. 내용은 제가 영어로 드릴게요, 한국어로 다듬어 주실 분 구합니다.',
    category: 'SCHOOL',
    helpMethod: 'CHAT',
    status: 'WAITING',
    requester: {
      id: 6,
      email: 'ali@test.com',
      nickname: '알리',
      userType: 'INTERNATIONAL',
      university: '국민대학교',
      rating: 4.9,
      helpCount: 1,
      createdAt: '2026-03-09',
    },
    createdAt: '2026-03-15T13:30:00',
    updatedAt: '2026-03-15T13:30:00',
  },
  {
    id: 7,
    title: '건강보험 가입 방법 알려주세요',
    description: '유학생 건강보험 의무 가입 대상인데 어떻게 신청하는지 모르겠어요. 국민건강보험공단 방문이 필요한지, 온라인으로 가능한지도 알려주시면 감사해요.',
    category: 'HOSPITAL',
    helpMethod: 'VIDEO_CALL',
    status: 'WAITING',
    requester: {
      id: 7,
      email: 'fatima@test.com',
      nickname: '파티마',
      userType: 'INTERNATIONAL',
      university: '국민대학교',
      rating: 4.3,
      helpCount: 0,
      createdAt: '2026-03-14',
    },
    createdAt: '2026-03-15T14:00:00',
    updatedAt: '2026-03-15T14:00:00',
  },
  {
    id: 8,
    title: '핸드폰 개통 같이 가주실 분 구해요',
    description: '한국 유심 개통하러 통신사 대리점 가야 하는데 혼자 가기 어려워요. 외국인 등록증 있고 서류도 준비했는데 직원이랑 대화하는 게 걱정돼요.',
    category: 'DAILY',
    helpMethod: 'OFFLINE',
    status: 'WAITING',
    requester: {
      id: 8,
      email: 'ivan@test.com',
      nickname: '이반',
      userType: 'INTERNATIONAL',
      university: '국민대학교',
      rating: 4.7,
      helpCount: 2,
      createdAt: '2026-03-10',
    },
    createdAt: '2026-03-14T16:00:00',
    updatedAt: '2026-03-14T16:00:00',
  },
  {
    id: 9,
    title: '기숙사 퇴실 청소 점검 기준 알려주세요',
    description: '학기 말에 기숙사 퇴실해야 하는데 청소 기준이 뭔지, 어떤 걸 체크하는지 모르겠어요. 보증금 환불받으려면 어떻게 해야 하나요?',
    category: 'SCHOOL',
    helpMethod: 'CHAT',
    status: 'MATCHED',
    requester: {
      id: 9,
      email: 'sakura@test.com',
      nickname: '사쿠라',
      userType: 'INTERNATIONAL',
      university: '국민대학교',
      rating: 5.0,
      helpCount: 3,
      createdAt: '2026-03-07',
    },
    createdAt: '2026-03-14T10:00:00',
    updatedAt: '2026-03-14T11:00:00',
  },
  {
    id: 10,
    title: 'KB국민은행 앱 설치 및 설정 도움',
    description: 'KB국민은행 앱을 깔았는데 공인인증서 설정하는 부분에서 막혀요. 영상통화로 같이 해주실 수 있나요? 30분 정도면 될 것 같아요.',
    category: 'BANK',
    helpMethod: 'VIDEO_CALL',
    status: 'WAITING',
    requester: {
      id: 10,
      email: 'dmitri@test.com',
      nickname: '드미트리',
      userType: 'INTERNATIONAL',
      university: '국민대학교',
      rating: 4.4,
      helpCount: 1,
      createdAt: '2026-03-11',
    },
    createdAt: '2026-03-13T09:00:00',
    updatedAt: '2026-03-13T09:00:00',
  },
];
